repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        types: [nix]

      - id: deadnix
        name: deadnix
        entry: deadnix --fail
        language: system
        types: [nix]

      - id: statix
        name: statix
        entry: statix check
        language: system
        types: [nix]
