name: Update dependencies

on:
  workflow_dispatch:
    inputs:
      packages:
        description: Specific packages to update (space-separated, empty for all)
        required: false
        default: ""
      inputs:
        description: Specific flake inputs to update (space-separated, empty for all)
        required: false
        default: ""
  schedule:
    - cron: "0 3 * * 1"

jobs:
  update:
    uses: ./.github/workflows/update-flake.yml
    with:
      packages: ${{ inputs.packages }}
      inputs: ${{ inputs.inputs }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
